[scripts]
# Uvicorn sunucusunu başlatmak için kullanılacak komut.
start = "uvicorn server.main:app --host=0.0.0.0 --port=${PORT:-8000}"

[build]
# Build işlemi sırasında çalıştırılacak komutlar.
commands = [
  # Python paketlerini yüklemek için pip kullanılır.
  "pip install -r requirements.txt"
]

[dependencies]
# Uygulamanızın bağımlılıklarını otomatik olarak çözümlemesini istemiyorsanız, 
# aşağıdaki satırı yorumdan çıkarabilirsiniz.
python = "3.9"
